version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Install requirements
          command: |
            export PYTHONPATH="$PYTHONPATH:$this_path/src"
            pip install --quiet -r "$this_path/requirements.txt"

      - run:
          name: Start docker compose stack and run tests
          command: IS_CI=true ./run_atests

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/
          destination: robot-results/

workflows:
  version: 2
  atests:
    jobs:
      - build
