version: 2

jobs:
  build:
    machine:
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: Run tests for docker-compose
          command: ./run_atests

      - store_test_results:
          path: results/

      - store_artifacts:
          path: results/
          destination: robot-results/

workflows:
  version: 2
  rfdocker:
    jobs:
      - build
